// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message/BulkImportMessage.proto

package QikkDB.NetworkClient.Message;

public final class BulkImportMessageOuterClass {
  private BulkImportMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BulkImportMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QikkDB.NetworkClient.Message.BulkImportMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string TableName = 1;</code>
     * @return The tableName.
     */
    java.lang.String getTableName();
    /**
     * <code>string TableName = 1;</code>
     * @return The bytes for tableName.
     */
    com.google.protobuf.ByteString
        getTableNameBytes();

    /**
     * <code>string ColumnName = 2;</code>
     * @return The columnName.
     */
    java.lang.String getColumnName();
    /**
     * <code>string ColumnName = 2;</code>
     * @return The bytes for columnName.
     */
    com.google.protobuf.ByteString
        getColumnNameBytes();

    /**
     * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
     * @return The enum numeric value on the wire for columnType.
     */
    int getColumnTypeValue();
    /**
     * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
     * @return The columnType.
     */
    QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType getColumnType();

    /**
     * <code>int32 ElemCount = 4;</code>
     * @return The elemCount.
     */
    int getElemCount();

    /**
     * <code>int32 nullMaskLen = 5;</code>
     * @return The nullMaskLen.
     */
    int getNullMaskLen();

    /**
     * <code>int32 dataLength = 6;</code>
     * @return The dataLength.
     */
    int getDataLength();
  }
  /**
   * Protobuf type {@code QikkDB.NetworkClient.Message.BulkImportMessage}
   */
  public  static final class BulkImportMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QikkDB.NetworkClient.Message.BulkImportMessage)
      BulkImportMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BulkImportMessage.newBuilder() to construct.
    private BulkImportMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BulkImportMessage() {
      tableName_ = "";
      columnName_ = "";
      columnType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BulkImportMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BulkImportMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              tableName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              columnName_ = s;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              columnType_ = rawValue;
              break;
            }
            case 32: {

              elemCount_ = input.readInt32();
              break;
            }
            case 40: {

              nullMaskLen_ = input.readInt32();
              break;
            }
            case 48: {

              dataLength_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.class, QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.Builder.class);
    }

    public static final int TABLENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object tableName_;
    /**
     * <code>string TableName = 1;</code>
     * @return The tableName.
     */
    public java.lang.String getTableName() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        tableName_ = s;
        return s;
      }
    }
    /**
     * <code>string TableName = 1;</code>
     * @return The bytes for tableName.
     */
    public com.google.protobuf.ByteString
        getTableNameBytes() {
      java.lang.Object ref = tableName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tableName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object columnName_;
    /**
     * <code>string ColumnName = 2;</code>
     * @return The columnName.
     */
    public java.lang.String getColumnName() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        columnName_ = s;
        return s;
      }
    }
    /**
     * <code>string ColumnName = 2;</code>
     * @return The bytes for columnName.
     */
    public com.google.protobuf.ByteString
        getColumnNameBytes() {
      java.lang.Object ref = columnName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        columnName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COLUMNTYPE_FIELD_NUMBER = 3;
    private int columnType_;
    /**
     * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
     * @return The enum numeric value on the wire for columnType.
     */
    public int getColumnTypeValue() {
      return columnType_;
    }
    /**
     * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
     * @return The columnType.
     */
    public QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType getColumnType() {
      @SuppressWarnings("deprecation")
      QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType result = QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType.valueOf(columnType_);
      return result == null ? QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType.UNRECOGNIZED : result;
    }

    public static final int ELEMCOUNT_FIELD_NUMBER = 4;
    private int elemCount_;
    /**
     * <code>int32 ElemCount = 4;</code>
     * @return The elemCount.
     */
    public int getElemCount() {
      return elemCount_;
    }

    public static final int NULLMASKLEN_FIELD_NUMBER = 5;
    private int nullMaskLen_;
    /**
     * <code>int32 nullMaskLen = 5;</code>
     * @return The nullMaskLen.
     */
    public int getNullMaskLen() {
      return nullMaskLen_;
    }

    public static final int DATALENGTH_FIELD_NUMBER = 6;
    private int dataLength_;
    /**
     * <code>int32 dataLength = 6;</code>
     * @return The dataLength.
     */
    public int getDataLength() {
      return dataLength_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTableNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, tableName_);
      }
      if (!getColumnNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, columnName_);
      }
      if (columnType_ != QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType.CONST_INT.getNumber()) {
        output.writeEnum(3, columnType_);
      }
      if (elemCount_ != 0) {
        output.writeInt32(4, elemCount_);
      }
      if (nullMaskLen_ != 0) {
        output.writeInt32(5, nullMaskLen_);
      }
      if (dataLength_ != 0) {
        output.writeInt32(6, dataLength_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTableNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, tableName_);
      }
      if (!getColumnNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, columnName_);
      }
      if (columnType_ != QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType.CONST_INT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, columnType_);
      }
      if (elemCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, elemCount_);
      }
      if (nullMaskLen_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, nullMaskLen_);
      }
      if (dataLength_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, dataLength_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage)) {
        return super.equals(obj);
      }
      QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage other = (QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage) obj;

      if (!getTableName()
          .equals(other.getTableName())) return false;
      if (!getColumnName()
          .equals(other.getColumnName())) return false;
      if (columnType_ != other.columnType_) return false;
      if (getElemCount()
          != other.getElemCount()) return false;
      if (getNullMaskLen()
          != other.getNullMaskLen()) return false;
      if (getDataLength()
          != other.getDataLength()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TABLENAME_FIELD_NUMBER;
      hash = (53 * hash) + getTableName().hashCode();
      hash = (37 * hash) + COLUMNNAME_FIELD_NUMBER;
      hash = (53 * hash) + getColumnName().hashCode();
      hash = (37 * hash) + COLUMNTYPE_FIELD_NUMBER;
      hash = (53 * hash) + columnType_;
      hash = (37 * hash) + ELEMCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getElemCount();
      hash = (37 * hash) + NULLMASKLEN_FIELD_NUMBER;
      hash = (53 * hash) + getNullMaskLen();
      hash = (37 * hash) + DATALENGTH_FIELD_NUMBER;
      hash = (53 * hash) + getDataLength();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QikkDB.NetworkClient.Message.BulkImportMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QikkDB.NetworkClient.Message.BulkImportMessage)
        QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.class, QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.Builder.class);
      }

      // Construct using QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        tableName_ = "";

        columnName_ = "";

        columnType_ = 0;

        elemCount_ = 0;

        nullMaskLen_ = 0;

        dataLength_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_descriptor;
      }

      @java.lang.Override
      public QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage getDefaultInstanceForType() {
        return QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.getDefaultInstance();
      }

      @java.lang.Override
      public QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage build() {
        QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage buildPartial() {
        QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage result = new QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage(this);
        result.tableName_ = tableName_;
        result.columnName_ = columnName_;
        result.columnType_ = columnType_;
        result.elemCount_ = elemCount_;
        result.nullMaskLen_ = nullMaskLen_;
        result.dataLength_ = dataLength_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage) {
          return mergeFrom((QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage other) {
        if (other == QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage.getDefaultInstance()) return this;
        if (!other.getTableName().isEmpty()) {
          tableName_ = other.tableName_;
          onChanged();
        }
        if (!other.getColumnName().isEmpty()) {
          columnName_ = other.columnName_;
          onChanged();
        }
        if (other.columnType_ != 0) {
          setColumnTypeValue(other.getColumnTypeValue());
        }
        if (other.getElemCount() != 0) {
          setElemCount(other.getElemCount());
        }
        if (other.getNullMaskLen() != 0) {
          setNullMaskLen(other.getNullMaskLen());
        }
        if (other.getDataLength() != 0) {
          setDataLength(other.getDataLength());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object tableName_ = "";
      /**
       * <code>string TableName = 1;</code>
       * @return The tableName.
       */
      public java.lang.String getTableName() {
        java.lang.Object ref = tableName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          tableName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string TableName = 1;</code>
       * @return The bytes for tableName.
       */
      public com.google.protobuf.ByteString
          getTableNameBytes() {
        java.lang.Object ref = tableName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tableName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string TableName = 1;</code>
       * @param value The tableName to set.
       * @return This builder for chaining.
       */
      public Builder setTableName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        tableName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string TableName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTableName() {
        
        tableName_ = getDefaultInstance().getTableName();
        onChanged();
        return this;
      }
      /**
       * <code>string TableName = 1;</code>
       * @param value The bytes for tableName to set.
       * @return This builder for chaining.
       */
      public Builder setTableNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        tableName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object columnName_ = "";
      /**
       * <code>string ColumnName = 2;</code>
       * @return The columnName.
       */
      public java.lang.String getColumnName() {
        java.lang.Object ref = columnName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          columnName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ColumnName = 2;</code>
       * @return The bytes for columnName.
       */
      public com.google.protobuf.ByteString
          getColumnNameBytes() {
        java.lang.Object ref = columnName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          columnName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ColumnName = 2;</code>
       * @param value The columnName to set.
       * @return This builder for chaining.
       */
      public Builder setColumnName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        columnName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ColumnName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumnName() {
        
        columnName_ = getDefaultInstance().getColumnName();
        onChanged();
        return this;
      }
      /**
       * <code>string ColumnName = 2;</code>
       * @param value The bytes for columnName to set.
       * @return This builder for chaining.
       */
      public Builder setColumnNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        columnName_ = value;
        onChanged();
        return this;
      }

      private int columnType_ = 0;
      /**
       * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
       * @return The enum numeric value on the wire for columnType.
       */
      public int getColumnTypeValue() {
        return columnType_;
      }
      /**
       * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
       * @param value The enum numeric value on the wire for columnType to set.
       * @return This builder for chaining.
       */
      public Builder setColumnTypeValue(int value) {
        columnType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
       * @return The columnType.
       */
      public QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType getColumnType() {
        @SuppressWarnings("deprecation")
        QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType result = QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType.valueOf(columnType_);
        return result == null ? QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType.UNRECOGNIZED : result;
      }
      /**
       * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
       * @param value The columnType to set.
       * @return This builder for chaining.
       */
      public Builder setColumnType(QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        columnType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.QikkDB.NetworkClient.Message.DataType ColumnType = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearColumnType() {
        
        columnType_ = 0;
        onChanged();
        return this;
      }

      private int elemCount_ ;
      /**
       * <code>int32 ElemCount = 4;</code>
       * @return The elemCount.
       */
      public int getElemCount() {
        return elemCount_;
      }
      /**
       * <code>int32 ElemCount = 4;</code>
       * @param value The elemCount to set.
       * @return This builder for chaining.
       */
      public Builder setElemCount(int value) {
        
        elemCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 ElemCount = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearElemCount() {
        
        elemCount_ = 0;
        onChanged();
        return this;
      }

      private int nullMaskLen_ ;
      /**
       * <code>int32 nullMaskLen = 5;</code>
       * @return The nullMaskLen.
       */
      public int getNullMaskLen() {
        return nullMaskLen_;
      }
      /**
       * <code>int32 nullMaskLen = 5;</code>
       * @param value The nullMaskLen to set.
       * @return This builder for chaining.
       */
      public Builder setNullMaskLen(int value) {
        
        nullMaskLen_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 nullMaskLen = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearNullMaskLen() {
        
        nullMaskLen_ = 0;
        onChanged();
        return this;
      }

      private int dataLength_ ;
      /**
       * <code>int32 dataLength = 6;</code>
       * @return The dataLength.
       */
      public int getDataLength() {
        return dataLength_;
      }
      /**
       * <code>int32 dataLength = 6;</code>
       * @param value The dataLength to set.
       * @return This builder for chaining.
       */
      public Builder setDataLength(int value) {
        
        dataLength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 dataLength = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataLength() {
        
        dataLength_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QikkDB.NetworkClient.Message.BulkImportMessage)
    }

    // @@protoc_insertion_point(class_scope:QikkDB.NetworkClient.Message.BulkImportMessage)
    private static final QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage();
    }

    public static QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BulkImportMessage>
        PARSER = new com.google.protobuf.AbstractParser<BulkImportMessage>() {
      @java.lang.Override
      public BulkImportMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BulkImportMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BulkImportMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BulkImportMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QikkDB.NetworkClient.Message.BulkImportMessageOuterClass.BulkImportMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037Message/BulkImportMessage.proto\022\034QikkD" +
      "B.NetworkClient.Message\032\036Message/CSVImpo" +
      "rtMessage.proto\"\262\001\n\021BulkImportMessage\022\021\n" +
      "\tTableName\030\001 \001(\t\022\022\n\nColumnName\030\002 \001(\t\022:\n\n" +
      "ColumnType\030\003 \001(\0162&.QikkDB.NetworkClient." +
      "Message.DataType\022\021\n\tElemCount\030\004 \001(\005\022\023\n\013n" +
      "ullMaskLen\030\005 \001(\005\022\022\n\ndataLength\030\006 \001(\005b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.getDescriptor(),
        });
    internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QikkDB_NetworkClient_Message_BulkImportMessage_descriptor,
        new java.lang.String[] { "TableName", "ColumnName", "ColumnType", "ElemCount", "NullMaskLen", "DataLength", });
    QikkDB.NetworkClient.Message.CSVImportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
