// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message/SetDatabaseMessage.proto

package QikkDB.NetworkClient.Message;

public final class SetDatabaseMessageOuterClass {
  private SetDatabaseMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SetDatabaseMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QikkDB.NetworkClient.Message.SetDatabaseMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string DatabaseName = 1;</code>
     * @return The databaseName.
     */
    java.lang.String getDatabaseName();
    /**
     * <code>string DatabaseName = 1;</code>
     * @return The bytes for databaseName.
     */
    com.google.protobuf.ByteString
        getDatabaseNameBytes();
  }
  /**
   * Protobuf type {@code QikkDB.NetworkClient.Message.SetDatabaseMessage}
   */
  public  static final class SetDatabaseMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QikkDB.NetworkClient.Message.SetDatabaseMessage)
      SetDatabaseMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SetDatabaseMessage.newBuilder() to construct.
    private SetDatabaseMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SetDatabaseMessage() {
      databaseName_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new SetDatabaseMessage();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetDatabaseMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              databaseName_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.class, QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.Builder.class);
    }

    public static final int DATABASENAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object databaseName_;
    /**
     * <code>string DatabaseName = 1;</code>
     * @return The databaseName.
     */
    public java.lang.String getDatabaseName() {
      java.lang.Object ref = databaseName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        databaseName_ = s;
        return s;
      }
    }
    /**
     * <code>string DatabaseName = 1;</code>
     * @return The bytes for databaseName.
     */
    public com.google.protobuf.ByteString
        getDatabaseNameBytes() {
      java.lang.Object ref = databaseName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        databaseName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDatabaseNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, databaseName_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDatabaseNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, databaseName_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage)) {
        return super.equals(obj);
      }
      QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage other = (QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage) obj;

      if (!getDatabaseName()
          .equals(other.getDatabaseName())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATABASENAME_FIELD_NUMBER;
      hash = (53 * hash) + getDatabaseName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QikkDB.NetworkClient.Message.SetDatabaseMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QikkDB.NetworkClient.Message.SetDatabaseMessage)
        QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.class, QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.Builder.class);
      }

      // Construct using QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        databaseName_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_descriptor;
      }

      @java.lang.Override
      public QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage getDefaultInstanceForType() {
        return QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.getDefaultInstance();
      }

      @java.lang.Override
      public QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage build() {
        QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage buildPartial() {
        QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage result = new QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage(this);
        result.databaseName_ = databaseName_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage) {
          return mergeFrom((QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage other) {
        if (other == QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage.getDefaultInstance()) return this;
        if (!other.getDatabaseName().isEmpty()) {
          databaseName_ = other.databaseName_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object databaseName_ = "";
      /**
       * <code>string DatabaseName = 1;</code>
       * @return The databaseName.
       */
      public java.lang.String getDatabaseName() {
        java.lang.Object ref = databaseName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          databaseName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string DatabaseName = 1;</code>
       * @return The bytes for databaseName.
       */
      public com.google.protobuf.ByteString
          getDatabaseNameBytes() {
        java.lang.Object ref = databaseName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          databaseName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string DatabaseName = 1;</code>
       * @param value The databaseName to set.
       * @return This builder for chaining.
       */
      public Builder setDatabaseName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        databaseName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string DatabaseName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatabaseName() {
        
        databaseName_ = getDefaultInstance().getDatabaseName();
        onChanged();
        return this;
      }
      /**
       * <code>string DatabaseName = 1;</code>
       * @param value The bytes for databaseName to set.
       * @return This builder for chaining.
       */
      public Builder setDatabaseNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        databaseName_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QikkDB.NetworkClient.Message.SetDatabaseMessage)
    }

    // @@protoc_insertion_point(class_scope:QikkDB.NetworkClient.Message.SetDatabaseMessage)
    private static final QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage();
    }

    public static QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SetDatabaseMessage>
        PARSER = new com.google.protobuf.AbstractParser<SetDatabaseMessage>() {
      @java.lang.Override
      public SetDatabaseMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SetDatabaseMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SetDatabaseMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetDatabaseMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QikkDB.NetworkClient.Message.SetDatabaseMessageOuterClass.SetDatabaseMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n Message/SetDatabaseMessage.proto\022\034Qikk" +
      "DB.NetworkClient.Message\"*\n\022SetDatabaseM" +
      "essage\022\024\n\014DatabaseName\030\001 \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QikkDB_NetworkClient_Message_SetDatabaseMessage_descriptor,
        new java.lang.String[] { "DatabaseName", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
