// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types/ComplexPolygon.proto

package QikkDB.Types;

public final class ComplexPolygonOuterClass {
  private ComplexPolygonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ComplexPolygonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QikkDB.Types.ComplexPolygon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    java.util.List<QikkDB.Types.ComplexPolygonOuterClass.Polygon> 
        getPolygonsList();
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    QikkDB.Types.ComplexPolygonOuterClass.Polygon getPolygons(int index);
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    int getPolygonsCount();
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    java.util.List<? extends QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder> 
        getPolygonsOrBuilderList();
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder getPolygonsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code QikkDB.Types.ComplexPolygon}
   */
  public  static final class ComplexPolygon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QikkDB.Types.ComplexPolygon)
      ComplexPolygonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ComplexPolygon.newBuilder() to construct.
    private ComplexPolygon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ComplexPolygon() {
      polygons_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ComplexPolygon();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ComplexPolygon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                polygons_ = new java.util.ArrayList<QikkDB.Types.ComplexPolygonOuterClass.Polygon>();
                mutable_bitField0_ |= 0x00000001;
              }
              polygons_.add(
                  input.readMessage(QikkDB.Types.ComplexPolygonOuterClass.Polygon.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          polygons_ = java.util.Collections.unmodifiableList(polygons_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_ComplexPolygon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_ComplexPolygon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.class, QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.Builder.class);
    }

    public static final int POLYGONS_FIELD_NUMBER = 1;
    private java.util.List<QikkDB.Types.ComplexPolygonOuterClass.Polygon> polygons_;
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    public java.util.List<QikkDB.Types.ComplexPolygonOuterClass.Polygon> getPolygonsList() {
      return polygons_;
    }
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    public java.util.List<? extends QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder> 
        getPolygonsOrBuilderList() {
      return polygons_;
    }
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    public int getPolygonsCount() {
      return polygons_.size();
    }
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    public QikkDB.Types.ComplexPolygonOuterClass.Polygon getPolygons(int index) {
      return polygons_.get(index);
    }
    /**
     * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
     */
    public QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder getPolygonsOrBuilder(
        int index) {
      return polygons_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < polygons_.size(); i++) {
        output.writeMessage(1, polygons_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < polygons_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, polygons_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon)) {
        return super.equals(obj);
      }
      QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon other = (QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon) obj;

      if (!getPolygonsList()
          .equals(other.getPolygonsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPolygonsCount() > 0) {
        hash = (37 * hash) + POLYGONS_FIELD_NUMBER;
        hash = (53 * hash) + getPolygonsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QikkDB.Types.ComplexPolygon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QikkDB.Types.ComplexPolygon)
        QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_ComplexPolygon_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_ComplexPolygon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.class, QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.Builder.class);
      }

      // Construct using QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPolygonsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (polygonsBuilder_ == null) {
          polygons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          polygonsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_ComplexPolygon_descriptor;
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon getDefaultInstanceForType() {
        return QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.getDefaultInstance();
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon build() {
        QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon buildPartial() {
        QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon result = new QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon(this);
        int from_bitField0_ = bitField0_;
        if (polygonsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            polygons_ = java.util.Collections.unmodifiableList(polygons_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.polygons_ = polygons_;
        } else {
          result.polygons_ = polygonsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon) {
          return mergeFrom((QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon other) {
        if (other == QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon.getDefaultInstance()) return this;
        if (polygonsBuilder_ == null) {
          if (!other.polygons_.isEmpty()) {
            if (polygons_.isEmpty()) {
              polygons_ = other.polygons_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePolygonsIsMutable();
              polygons_.addAll(other.polygons_);
            }
            onChanged();
          }
        } else {
          if (!other.polygons_.isEmpty()) {
            if (polygonsBuilder_.isEmpty()) {
              polygonsBuilder_.dispose();
              polygonsBuilder_ = null;
              polygons_ = other.polygons_;
              bitField0_ = (bitField0_ & ~0x00000001);
              polygonsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPolygonsFieldBuilder() : null;
            } else {
              polygonsBuilder_.addAllMessages(other.polygons_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<QikkDB.Types.ComplexPolygonOuterClass.Polygon> polygons_ =
        java.util.Collections.emptyList();
      private void ensurePolygonsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          polygons_ = new java.util.ArrayList<QikkDB.Types.ComplexPolygonOuterClass.Polygon>(polygons_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          QikkDB.Types.ComplexPolygonOuterClass.Polygon, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder, QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder> polygonsBuilder_;

      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public java.util.List<QikkDB.Types.ComplexPolygonOuterClass.Polygon> getPolygonsList() {
        if (polygonsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(polygons_);
        } else {
          return polygonsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public int getPolygonsCount() {
        if (polygonsBuilder_ == null) {
          return polygons_.size();
        } else {
          return polygonsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon getPolygons(int index) {
        if (polygonsBuilder_ == null) {
          return polygons_.get(index);
        } else {
          return polygonsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder setPolygons(
          int index, QikkDB.Types.ComplexPolygonOuterClass.Polygon value) {
        if (polygonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePolygonsIsMutable();
          polygons_.set(index, value);
          onChanged();
        } else {
          polygonsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder setPolygons(
          int index, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder builderForValue) {
        if (polygonsBuilder_ == null) {
          ensurePolygonsIsMutable();
          polygons_.set(index, builderForValue.build());
          onChanged();
        } else {
          polygonsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder addPolygons(QikkDB.Types.ComplexPolygonOuterClass.Polygon value) {
        if (polygonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePolygonsIsMutable();
          polygons_.add(value);
          onChanged();
        } else {
          polygonsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder addPolygons(
          int index, QikkDB.Types.ComplexPolygonOuterClass.Polygon value) {
        if (polygonsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePolygonsIsMutable();
          polygons_.add(index, value);
          onChanged();
        } else {
          polygonsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder addPolygons(
          QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder builderForValue) {
        if (polygonsBuilder_ == null) {
          ensurePolygonsIsMutable();
          polygons_.add(builderForValue.build());
          onChanged();
        } else {
          polygonsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder addPolygons(
          int index, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder builderForValue) {
        if (polygonsBuilder_ == null) {
          ensurePolygonsIsMutable();
          polygons_.add(index, builderForValue.build());
          onChanged();
        } else {
          polygonsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder addAllPolygons(
          java.lang.Iterable<? extends QikkDB.Types.ComplexPolygonOuterClass.Polygon> values) {
        if (polygonsBuilder_ == null) {
          ensurePolygonsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, polygons_);
          onChanged();
        } else {
          polygonsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder clearPolygons() {
        if (polygonsBuilder_ == null) {
          polygons_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          polygonsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public Builder removePolygons(int index) {
        if (polygonsBuilder_ == null) {
          ensurePolygonsIsMutable();
          polygons_.remove(index);
          onChanged();
        } else {
          polygonsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder getPolygonsBuilder(
          int index) {
        return getPolygonsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder getPolygonsOrBuilder(
          int index) {
        if (polygonsBuilder_ == null) {
          return polygons_.get(index);  } else {
          return polygonsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public java.util.List<? extends QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder> 
           getPolygonsOrBuilderList() {
        if (polygonsBuilder_ != null) {
          return polygonsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(polygons_);
        }
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder addPolygonsBuilder() {
        return getPolygonsFieldBuilder().addBuilder(
            QikkDB.Types.ComplexPolygonOuterClass.Polygon.getDefaultInstance());
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder addPolygonsBuilder(
          int index) {
        return getPolygonsFieldBuilder().addBuilder(
            index, QikkDB.Types.ComplexPolygonOuterClass.Polygon.getDefaultInstance());
      }
      /**
       * <code>repeated .QikkDB.Types.Polygon polygons = 1;</code>
       */
      public java.util.List<QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder> 
           getPolygonsBuilderList() {
        return getPolygonsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          QikkDB.Types.ComplexPolygonOuterClass.Polygon, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder, QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder> 
          getPolygonsFieldBuilder() {
        if (polygonsBuilder_ == null) {
          polygonsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              QikkDB.Types.ComplexPolygonOuterClass.Polygon, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder, QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder>(
                  polygons_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          polygons_ = null;
        }
        return polygonsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QikkDB.Types.ComplexPolygon)
    }

    // @@protoc_insertion_point(class_scope:QikkDB.Types.ComplexPolygon)
    private static final QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon();
    }

    public static QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ComplexPolygon>
        PARSER = new com.google.protobuf.AbstractParser<ComplexPolygon>() {
      @java.lang.Override
      public ComplexPolygon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ComplexPolygon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ComplexPolygon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ComplexPolygon> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QikkDB.Types.ComplexPolygonOuterClass.ComplexPolygon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PolygonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QikkDB.Types.Polygon)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    java.util.List<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint> 
        getGeoPointsList();
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getGeoPoints(int index);
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    int getGeoPointsCount();
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    java.util.List<? extends QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> 
        getGeoPointsOrBuilderList();
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder getGeoPointsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code QikkDB.Types.Polygon}
   */
  public  static final class Polygon extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QikkDB.Types.Polygon)
      PolygonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Polygon.newBuilder() to construct.
    private Polygon(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Polygon() {
      geoPoints_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Polygon();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Polygon(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                geoPoints_ = new java.util.ArrayList<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint>();
                mutable_bitField0_ |= 0x00000001;
              }
              geoPoints_.add(
                  input.readMessage(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          geoPoints_ = java.util.Collections.unmodifiableList(geoPoints_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_Polygon_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_Polygon_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QikkDB.Types.ComplexPolygonOuterClass.Polygon.class, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder.class);
    }

    public static final int GEOPOINTS_FIELD_NUMBER = 1;
    private java.util.List<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint> geoPoints_;
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    public java.util.List<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint> getGeoPointsList() {
      return geoPoints_;
    }
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    public java.util.List<? extends QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> 
        getGeoPointsOrBuilderList() {
      return geoPoints_;
    }
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    public int getGeoPointsCount() {
      return geoPoints_.size();
    }
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getGeoPoints(int index) {
      return geoPoints_.get(index);
    }
    /**
     * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
     */
    public QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder getGeoPointsOrBuilder(
        int index) {
      return geoPoints_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < geoPoints_.size(); i++) {
        output.writeMessage(1, geoPoints_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < geoPoints_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, geoPoints_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QikkDB.Types.ComplexPolygonOuterClass.Polygon)) {
        return super.equals(obj);
      }
      QikkDB.Types.ComplexPolygonOuterClass.Polygon other = (QikkDB.Types.ComplexPolygonOuterClass.Polygon) obj;

      if (!getGeoPointsList()
          .equals(other.getGeoPointsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getGeoPointsCount() > 0) {
        hash = (37 * hash) + GEOPOINTS_FIELD_NUMBER;
        hash = (53 * hash) + getGeoPointsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QikkDB.Types.ComplexPolygonOuterClass.Polygon prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QikkDB.Types.Polygon}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QikkDB.Types.Polygon)
        QikkDB.Types.ComplexPolygonOuterClass.PolygonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_Polygon_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_Polygon_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QikkDB.Types.ComplexPolygonOuterClass.Polygon.class, QikkDB.Types.ComplexPolygonOuterClass.Polygon.Builder.class);
      }

      // Construct using QikkDB.Types.ComplexPolygonOuterClass.Polygon.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGeoPointsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (geoPointsBuilder_ == null) {
          geoPoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          geoPointsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_Polygon_descriptor;
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon getDefaultInstanceForType() {
        return QikkDB.Types.ComplexPolygonOuterClass.Polygon.getDefaultInstance();
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon build() {
        QikkDB.Types.ComplexPolygonOuterClass.Polygon result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.Polygon buildPartial() {
        QikkDB.Types.ComplexPolygonOuterClass.Polygon result = new QikkDB.Types.ComplexPolygonOuterClass.Polygon(this);
        int from_bitField0_ = bitField0_;
        if (geoPointsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            geoPoints_ = java.util.Collections.unmodifiableList(geoPoints_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.geoPoints_ = geoPoints_;
        } else {
          result.geoPoints_ = geoPointsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QikkDB.Types.ComplexPolygonOuterClass.Polygon) {
          return mergeFrom((QikkDB.Types.ComplexPolygonOuterClass.Polygon)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QikkDB.Types.ComplexPolygonOuterClass.Polygon other) {
        if (other == QikkDB.Types.ComplexPolygonOuterClass.Polygon.getDefaultInstance()) return this;
        if (geoPointsBuilder_ == null) {
          if (!other.geoPoints_.isEmpty()) {
            if (geoPoints_.isEmpty()) {
              geoPoints_ = other.geoPoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureGeoPointsIsMutable();
              geoPoints_.addAll(other.geoPoints_);
            }
            onChanged();
          }
        } else {
          if (!other.geoPoints_.isEmpty()) {
            if (geoPointsBuilder_.isEmpty()) {
              geoPointsBuilder_.dispose();
              geoPointsBuilder_ = null;
              geoPoints_ = other.geoPoints_;
              bitField0_ = (bitField0_ & ~0x00000001);
              geoPointsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGeoPointsFieldBuilder() : null;
            } else {
              geoPointsBuilder_.addAllMessages(other.geoPoints_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QikkDB.Types.ComplexPolygonOuterClass.Polygon parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QikkDB.Types.ComplexPolygonOuterClass.Polygon) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint> geoPoints_ =
        java.util.Collections.emptyList();
      private void ensureGeoPointsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          geoPoints_ = new java.util.ArrayList<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint>(geoPoints_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          QikkDB.Types.ComplexPolygonOuterClass.GeoPoint, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder, QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> geoPointsBuilder_;

      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public java.util.List<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint> getGeoPointsList() {
        if (geoPointsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(geoPoints_);
        } else {
          return geoPointsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public int getGeoPointsCount() {
        if (geoPointsBuilder_ == null) {
          return geoPoints_.size();
        } else {
          return geoPointsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getGeoPoints(int index) {
        if (geoPointsBuilder_ == null) {
          return geoPoints_.get(index);
        } else {
          return geoPointsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder setGeoPoints(
          int index, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint value) {
        if (geoPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGeoPointsIsMutable();
          geoPoints_.set(index, value);
          onChanged();
        } else {
          geoPointsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder setGeoPoints(
          int index, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder builderForValue) {
        if (geoPointsBuilder_ == null) {
          ensureGeoPointsIsMutable();
          geoPoints_.set(index, builderForValue.build());
          onChanged();
        } else {
          geoPointsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder addGeoPoints(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint value) {
        if (geoPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGeoPointsIsMutable();
          geoPoints_.add(value);
          onChanged();
        } else {
          geoPointsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder addGeoPoints(
          int index, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint value) {
        if (geoPointsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGeoPointsIsMutable();
          geoPoints_.add(index, value);
          onChanged();
        } else {
          geoPointsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder addGeoPoints(
          QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder builderForValue) {
        if (geoPointsBuilder_ == null) {
          ensureGeoPointsIsMutable();
          geoPoints_.add(builderForValue.build());
          onChanged();
        } else {
          geoPointsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder addGeoPoints(
          int index, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder builderForValue) {
        if (geoPointsBuilder_ == null) {
          ensureGeoPointsIsMutable();
          geoPoints_.add(index, builderForValue.build());
          onChanged();
        } else {
          geoPointsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder addAllGeoPoints(
          java.lang.Iterable<? extends QikkDB.Types.ComplexPolygonOuterClass.GeoPoint> values) {
        if (geoPointsBuilder_ == null) {
          ensureGeoPointsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, geoPoints_);
          onChanged();
        } else {
          geoPointsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder clearGeoPoints() {
        if (geoPointsBuilder_ == null) {
          geoPoints_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          geoPointsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public Builder removeGeoPoints(int index) {
        if (geoPointsBuilder_ == null) {
          ensureGeoPointsIsMutable();
          geoPoints_.remove(index);
          onChanged();
        } else {
          geoPointsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder getGeoPointsBuilder(
          int index) {
        return getGeoPointsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder getGeoPointsOrBuilder(
          int index) {
        if (geoPointsBuilder_ == null) {
          return geoPoints_.get(index);  } else {
          return geoPointsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public java.util.List<? extends QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> 
           getGeoPointsOrBuilderList() {
        if (geoPointsBuilder_ != null) {
          return geoPointsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(geoPoints_);
        }
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder addGeoPointsBuilder() {
        return getGeoPointsFieldBuilder().addBuilder(
            QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance());
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder addGeoPointsBuilder(
          int index) {
        return getGeoPointsFieldBuilder().addBuilder(
            index, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance());
      }
      /**
       * <code>repeated .QikkDB.Types.GeoPoint geoPoints = 1;</code>
       */
      public java.util.List<QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder> 
           getGeoPointsBuilderList() {
        return getGeoPointsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          QikkDB.Types.ComplexPolygonOuterClass.GeoPoint, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder, QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> 
          getGeoPointsFieldBuilder() {
        if (geoPointsBuilder_ == null) {
          geoPointsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              QikkDB.Types.ComplexPolygonOuterClass.GeoPoint, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder, QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder>(
                  geoPoints_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          geoPoints_ = null;
        }
        return geoPointsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QikkDB.Types.Polygon)
    }

    // @@protoc_insertion_point(class_scope:QikkDB.Types.Polygon)
    private static final QikkDB.Types.ComplexPolygonOuterClass.Polygon DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QikkDB.Types.ComplexPolygonOuterClass.Polygon();
    }

    public static QikkDB.Types.ComplexPolygonOuterClass.Polygon getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Polygon>
        PARSER = new com.google.protobuf.AbstractParser<Polygon>() {
      @java.lang.Override
      public Polygon parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Polygon(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Polygon> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Polygon> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QikkDB.Types.ComplexPolygonOuterClass.Polygon getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeoPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QikkDB.Types.GeoPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float latitude = 1;</code>
     * @return The latitude.
     */
    float getLatitude();

    /**
     * <code>float longitude = 2;</code>
     * @return The longitude.
     */
    float getLongitude();
  }
  /**
   * Protobuf type {@code QikkDB.Types.GeoPoint}
   */
  public  static final class GeoPoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QikkDB.Types.GeoPoint)
      GeoPointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GeoPoint.newBuilder() to construct.
    private GeoPoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GeoPoint() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new GeoPoint();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GeoPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              latitude_ = input.readFloat();
              break;
            }
            case 21: {

              longitude_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_GeoPoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_GeoPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.class, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private float latitude_;
    /**
     * <code>float latitude = 1;</code>
     * @return The latitude.
     */
    public float getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private float longitude_;
    /**
     * <code>float longitude = 2;</code>
     * @return The longitude.
     */
    public float getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitude_ != 0F) {
        output.writeFloat(1, latitude_);
      }
      if (longitude_ != 0F) {
        output.writeFloat(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, latitude_);
      }
      if (longitude_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QikkDB.Types.ComplexPolygonOuterClass.GeoPoint)) {
        return super.equals(obj);
      }
      QikkDB.Types.ComplexPolygonOuterClass.GeoPoint other = (QikkDB.Types.ComplexPolygonOuterClass.GeoPoint) obj;

      if (java.lang.Float.floatToIntBits(getLatitude())
          != java.lang.Float.floatToIntBits(
              other.getLatitude())) return false;
      if (java.lang.Float.floatToIntBits(getLongitude())
          != java.lang.Float.floatToIntBits(
              other.getLongitude())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLatitude());
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLongitude());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QikkDB.Types.GeoPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QikkDB.Types.GeoPoint)
        QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_GeoPoint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_GeoPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.class, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder.class);
      }

      // Construct using QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitude_ = 0F;

        longitude_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QikkDB.Types.ComplexPolygonOuterClass.internal_static_QikkDB_Types_GeoPoint_descriptor;
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getDefaultInstanceForType() {
        return QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance();
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint build() {
        QikkDB.Types.ComplexPolygonOuterClass.GeoPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint buildPartial() {
        QikkDB.Types.ComplexPolygonOuterClass.GeoPoint result = new QikkDB.Types.ComplexPolygonOuterClass.GeoPoint(this);
        result.latitude_ = latitude_;
        result.longitude_ = longitude_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QikkDB.Types.ComplexPolygonOuterClass.GeoPoint) {
          return mergeFrom((QikkDB.Types.ComplexPolygonOuterClass.GeoPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint other) {
        if (other == QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance()) return this;
        if (other.getLatitude() != 0F) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0F) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QikkDB.Types.ComplexPolygonOuterClass.GeoPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QikkDB.Types.ComplexPolygonOuterClass.GeoPoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float latitude_ ;
      /**
       * <code>float latitude = 1;</code>
       * @return The latitude.
       */
      public float getLatitude() {
        return latitude_;
      }
      /**
       * <code>float latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(float value) {
        
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        
        latitude_ = 0F;
        onChanged();
        return this;
      }

      private float longitude_ ;
      /**
       * <code>float longitude = 2;</code>
       * @return The longitude.
       */
      public float getLongitude() {
        return longitude_;
      }
      /**
       * <code>float longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(float value) {
        
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        
        longitude_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QikkDB.Types.GeoPoint)
    }

    // @@protoc_insertion_point(class_scope:QikkDB.Types.GeoPoint)
    private static final QikkDB.Types.ComplexPolygonOuterClass.GeoPoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QikkDB.Types.ComplexPolygonOuterClass.GeoPoint();
    }

    public static QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GeoPoint>
        PARSER = new com.google.protobuf.AbstractParser<GeoPoint>() {
      @java.lang.Override
      public GeoPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GeoPoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GeoPoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GeoPoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QikkDB_Types_ComplexPolygon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QikkDB_Types_ComplexPolygon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QikkDB_Types_Polygon_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QikkDB_Types_Polygon_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QikkDB_Types_GeoPoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QikkDB_Types_GeoPoint_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032Types/ComplexPolygon.proto\022\014QikkDB.Typ" +
      "es\"9\n\016ComplexPolygon\022\'\n\010polygons\030\001 \003(\0132\025" +
      ".QikkDB.Types.Polygon\"4\n\007Polygon\022)\n\tgeoP" +
      "oints\030\001 \003(\0132\026.QikkDB.Types.GeoPoint\"/\n\010G" +
      "eoPoint\022\020\n\010latitude\030\001 \001(\002\022\021\n\tlongitude\030\002" +
      " \001(\002b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_QikkDB_Types_ComplexPolygon_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QikkDB_Types_ComplexPolygon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QikkDB_Types_ComplexPolygon_descriptor,
        new java.lang.String[] { "Polygons", });
    internal_static_QikkDB_Types_Polygon_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QikkDB_Types_Polygon_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QikkDB_Types_Polygon_descriptor,
        new java.lang.String[] { "GeoPoints", });
    internal_static_QikkDB_Types_GeoPoint_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_QikkDB_Types_GeoPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QikkDB_Types_GeoPoint_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
