// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Types/Point.proto

package QikkDB.Types;

public final class PointOuterClass {
  private PointOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:QikkDB.Types.Point)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
     * @return Whether the geoPoint field is set.
     */
    boolean hasGeoPoint();
    /**
     * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
     * @return The geoPoint.
     */
    QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getGeoPoint();
    /**
     * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
     */
    QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder getGeoPointOrBuilder();
  }
  /**
   * Protobuf type {@code QikkDB.Types.Point}
   */
  public  static final class Point extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:QikkDB.Types.Point)
      PointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Point.newBuilder() to construct.
    private Point(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Point() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Point();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Point(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder subBuilder = null;
              if (geoPoint_ != null) {
                subBuilder = geoPoint_.toBuilder();
              }
              geoPoint_ = input.readMessage(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(geoPoint_);
                geoPoint_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return QikkDB.Types.PointOuterClass.internal_static_QikkDB_Types_Point_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return QikkDB.Types.PointOuterClass.internal_static_QikkDB_Types_Point_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              QikkDB.Types.PointOuterClass.Point.class, QikkDB.Types.PointOuterClass.Point.Builder.class);
    }

    public static final int GEOPOINT_FIELD_NUMBER = 1;
    private QikkDB.Types.ComplexPolygonOuterClass.GeoPoint geoPoint_;
    /**
     * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
     * @return Whether the geoPoint field is set.
     */
    public boolean hasGeoPoint() {
      return geoPoint_ != null;
    }
    /**
     * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
     * @return The geoPoint.
     */
    public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getGeoPoint() {
      return geoPoint_ == null ? QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance() : geoPoint_;
    }
    /**
     * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
     */
    public QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder getGeoPointOrBuilder() {
      return getGeoPoint();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (geoPoint_ != null) {
        output.writeMessage(1, getGeoPoint());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (geoPoint_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getGeoPoint());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof QikkDB.Types.PointOuterClass.Point)) {
        return super.equals(obj);
      }
      QikkDB.Types.PointOuterClass.Point other = (QikkDB.Types.PointOuterClass.Point) obj;

      if (hasGeoPoint() != other.hasGeoPoint()) return false;
      if (hasGeoPoint()) {
        if (!getGeoPoint()
            .equals(other.getGeoPoint())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasGeoPoint()) {
        hash = (37 * hash) + GEOPOINT_FIELD_NUMBER;
        hash = (53 * hash) + getGeoPoint().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.PointOuterClass.Point parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static QikkDB.Types.PointOuterClass.Point parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static QikkDB.Types.PointOuterClass.Point parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(QikkDB.Types.PointOuterClass.Point prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code QikkDB.Types.Point}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:QikkDB.Types.Point)
        QikkDB.Types.PointOuterClass.PointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return QikkDB.Types.PointOuterClass.internal_static_QikkDB_Types_Point_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return QikkDB.Types.PointOuterClass.internal_static_QikkDB_Types_Point_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                QikkDB.Types.PointOuterClass.Point.class, QikkDB.Types.PointOuterClass.Point.Builder.class);
      }

      // Construct using QikkDB.Types.PointOuterClass.Point.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (geoPointBuilder_ == null) {
          geoPoint_ = null;
        } else {
          geoPoint_ = null;
          geoPointBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return QikkDB.Types.PointOuterClass.internal_static_QikkDB_Types_Point_descriptor;
      }

      @java.lang.Override
      public QikkDB.Types.PointOuterClass.Point getDefaultInstanceForType() {
        return QikkDB.Types.PointOuterClass.Point.getDefaultInstance();
      }

      @java.lang.Override
      public QikkDB.Types.PointOuterClass.Point build() {
        QikkDB.Types.PointOuterClass.Point result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public QikkDB.Types.PointOuterClass.Point buildPartial() {
        QikkDB.Types.PointOuterClass.Point result = new QikkDB.Types.PointOuterClass.Point(this);
        if (geoPointBuilder_ == null) {
          result.geoPoint_ = geoPoint_;
        } else {
          result.geoPoint_ = geoPointBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof QikkDB.Types.PointOuterClass.Point) {
          return mergeFrom((QikkDB.Types.PointOuterClass.Point)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(QikkDB.Types.PointOuterClass.Point other) {
        if (other == QikkDB.Types.PointOuterClass.Point.getDefaultInstance()) return this;
        if (other.hasGeoPoint()) {
          mergeGeoPoint(other.getGeoPoint());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        QikkDB.Types.PointOuterClass.Point parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (QikkDB.Types.PointOuterClass.Point) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private QikkDB.Types.ComplexPolygonOuterClass.GeoPoint geoPoint_;
      private com.google.protobuf.SingleFieldBuilderV3<
          QikkDB.Types.ComplexPolygonOuterClass.GeoPoint, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder, QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> geoPointBuilder_;
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       * @return Whether the geoPoint field is set.
       */
      public boolean hasGeoPoint() {
        return geoPointBuilder_ != null || geoPoint_ != null;
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       * @return The geoPoint.
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint getGeoPoint() {
        if (geoPointBuilder_ == null) {
          return geoPoint_ == null ? QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance() : geoPoint_;
        } else {
          return geoPointBuilder_.getMessage();
        }
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      public Builder setGeoPoint(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint value) {
        if (geoPointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          geoPoint_ = value;
          onChanged();
        } else {
          geoPointBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      public Builder setGeoPoint(
          QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder builderForValue) {
        if (geoPointBuilder_ == null) {
          geoPoint_ = builderForValue.build();
          onChanged();
        } else {
          geoPointBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      public Builder mergeGeoPoint(QikkDB.Types.ComplexPolygonOuterClass.GeoPoint value) {
        if (geoPointBuilder_ == null) {
          if (geoPoint_ != null) {
            geoPoint_ =
              QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.newBuilder(geoPoint_).mergeFrom(value).buildPartial();
          } else {
            geoPoint_ = value;
          }
          onChanged();
        } else {
          geoPointBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      public Builder clearGeoPoint() {
        if (geoPointBuilder_ == null) {
          geoPoint_ = null;
          onChanged();
        } else {
          geoPoint_ = null;
          geoPointBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder getGeoPointBuilder() {
        
        onChanged();
        return getGeoPointFieldBuilder().getBuilder();
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      public QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder getGeoPointOrBuilder() {
        if (geoPointBuilder_ != null) {
          return geoPointBuilder_.getMessageOrBuilder();
        } else {
          return geoPoint_ == null ?
              QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.getDefaultInstance() : geoPoint_;
        }
      }
      /**
       * <code>.QikkDB.Types.GeoPoint geoPoint = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          QikkDB.Types.ComplexPolygonOuterClass.GeoPoint, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder, QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder> 
          getGeoPointFieldBuilder() {
        if (geoPointBuilder_ == null) {
          geoPointBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              QikkDB.Types.ComplexPolygonOuterClass.GeoPoint, QikkDB.Types.ComplexPolygonOuterClass.GeoPoint.Builder, QikkDB.Types.ComplexPolygonOuterClass.GeoPointOrBuilder>(
                  getGeoPoint(),
                  getParentForChildren(),
                  isClean());
          geoPoint_ = null;
        }
        return geoPointBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:QikkDB.Types.Point)
    }

    // @@protoc_insertion_point(class_scope:QikkDB.Types.Point)
    private static final QikkDB.Types.PointOuterClass.Point DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new QikkDB.Types.PointOuterClass.Point();
    }

    public static QikkDB.Types.PointOuterClass.Point getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Point>
        PARSER = new com.google.protobuf.AbstractParser<Point>() {
      @java.lang.Override
      public Point parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Point(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Point> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Point> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public QikkDB.Types.PointOuterClass.Point getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QikkDB_Types_Point_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QikkDB_Types_Point_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Types/Point.proto\022\014QikkDB.Types\032\032Types" +
      "/ComplexPolygon.proto\"1\n\005Point\022(\n\010geoPoi" +
      "nt\030\001 \001(\0132\026.QikkDB.Types.GeoPointb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          QikkDB.Types.ComplexPolygonOuterClass.getDescriptor(),
        });
    internal_static_QikkDB_Types_Point_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QikkDB_Types_Point_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QikkDB_Types_Point_descriptor,
        new java.lang.String[] { "GeoPoint", });
    QikkDB.Types.ComplexPolygonOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
